name: Python Hello World Test

on: [push, pull_request]

jobs:
  test-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run Hello World script
      run: |
        python hello_world.py

    - name: Run Tests
      run: |
        pytest
